### ISSUE TITLE
Issues found while trying to register a new account on the current SaaS implementation

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/interoperability#234]
I was trying to create a new account and found some issues while trying to do so. Everything I've tried was done via the UI, so these errors can be either from back-end flow issues, or wrong implementations by the front-end:

1. ~~Trying to register an account with existing data returns internal server error.~~ fixed
2. The "last verification code still valid" error doesn't sound good. The normal behavior is to create a new verification code and send that instead.
3. ~~After discovering I could have a button to verify my account under the development environment, apparently it was too late and my verification code already expired (we're talking about a 5' delay maybe, but since I tried registering the account again and got that internal server error... maybe it's related).~~ 
4. ~~There's no way to verify an account under develop after 5' (?)~~ fixed by https://github.com/vocdoni/ui-scaffold/pull/829
![imatge](https://github.com/user-attachments/assets/cae47751-db67-45e5-9149-3af6e3bbfc12)
5. ~~Trying to login with a non existent account returns "user not authorized", which doesn't sound as a proper error message for this use case.~~ proper behavior
6. ~~Can't logout from my logged in account if I've not created any org yet.~~ The logout button should be more visible... it's down below the form, after the "if this is not your account, please logout". That "please logout" should also be a logout button.
7. ~~The organization creation form shows a confusing error at the bottom: "Account not found: 0x834DE..." where 0x834DE... is my currently logged in wallet 🤔~~  Metamask related
8. ~~From the "organization type" most types aren't implemented in the backend. The front-end should not be rendering unimplemented options.~~ Fixed
9. ~~When submitting the organization information, a metamask sign request to create my SIK is generated. Probably caused by running it locally on the same port I run most applications (and having a metamask session started in this same domain:port). After cancelling the sign request, a "user rejected transaction" error appeared, staying me on the "create organization" form. Login-out and login-in again apparently shows my organization created though.~~ Metamask related

(edited to include numeric indexes)

**Comment by lucasmenendez** [comment]
* **Topics 1 & 3**: now the registration endpoint returns a **409 Conflict** error with body ([see the docs](https://github.com/vocdoni/saas-backend/blob/main/api/docs.md#-register)):
```json
{
  "error": "duplicate conflict: user already exists",
  "code": 40901
}
```

* **Topics 2 & 4**: now the verification codes have an expiration time of [2 minutes](https://github.com/vocdoni/saas-backend/blob/23ed5ef6e18273d05e107c2e918cbc8636e9602b/api/const.go#L7). After this time, the expiration code is not valid and must be sent again. To manage this flow, there are two endpoints available, one to [check the information about a verification code by the email](https://github.com/vocdoni/saas-backend/blob/main/api/docs.md#-user-verification-code-info), and another to [resend a verification code to an unverified user](https://github.com/vocdoni/saas-backend/blob/main/api/docs.md#-resend-user-verification-code).

* **Topics 5 & 7**: I suggest not to show the errors that coming from the API directly in the UI, I think it is better to handle them and show specific messages to the users. The errors returned by the API may not be meaningful to the end user. If the UI needs more specific errors for some use cases, they can be implemented in the backend.

* **Topic 8**: as far as i know there is no single source of truth for organization types. For now, the backend has two types (`company` & `community`). I already suggested that they should be defined in the backend (where the validation of this data is done) and exposed in an API endpoint (if it is needed). And the same for the user roles (now `admin`, `manager` and `viewer`).

I do not answer to other topics because I think that there are no a backend issues.

cc/ @elboletaire @jpaulet

**Comment by jpaulet** [comment]
I would extend to expiration time to at least 5 min. 

The official list of "org" is:
- Assembly
- Association
- Chamber
- Church / Religious Organization
- City / Municipality
- Company / Corporation
- Cooperative
- Political Party
- University / Educational Institution
- Union
- Nonprofit / NGO
- Community Group
- Professional College
- Others

For the roles, is as you comment, "admin", "manager" and "viewer". 

We can create an endpoint that returns all this information (org types, admin types, country list..).

**Comment by lucasmenendez** [comment]
I have no preference on the expiration time of the verification codes, but keep this in mind:

The expiration time is not only the time that the user has to verify the account, it is also the time that the user has to wait for a verification code to be resent. So, if we extend this time and the code is not received by the user, he or she should wait more to complete the process...

@jpaulet

**Comment by jpaulet** [comment]
I know, but 2 minutes is not enough time. Let's start with at least 3 min.

**Comment by lucasmenendez** [comment]
> I would extend to expiration time to at least 5 min.
> 
> The official list of "org" is:
> 
> * Assembly
> * Association
> * Chamber
> * Church / Religious Organization
> * City / Municipality
> * Company / Corporation
> * Cooperative
> * Political Party
> * University / Educational Institution
> * Union
> * Nonprofit / NGO
> * Community Group
> * Professional College
> * Others
> 
> For the roles, is as you comment, "admin", "manager" and "viewer".
> 
> We can create an endpoint that returns all this information (org types, admin types, country list..).

PR created: https://github.com/vocdoni/saas-backend/pull/23

**Comment by elboletaire** [comment]
> Topics 5 & 7: I suggest not to show the errors that coming from the API directly in the UI, I think it is better to handle them and show specific messages to the users. The errors returned by the API may not be meaningful to the end user. If the UI needs more specific errors for some use cases, they can be implemented in the backend.

That's giving us double work. If they were meaningful to users would be easier to understand for end developers too, but also, there would be no need to intercept them and map error codes to different error strings. 

> Regarding the country list, it does not make sense to me to serve a list of countries from the backend. I understood that the front will get from an external API like the timezones for example.

Agree there's no need to implement this from the backend, but we should decide how to store them (I think we're storing the full country name, but may be better to store some kind of code, like alpha-2 or alpha-3). For the API to be used by the front, there are many options, like https://restcountries.com or https://countryapi.io. All of them return all the available codes, but still, storing them in full name could give us issues (full country names may vary depending on the language used).

For the timezones there are less options than for countries (I've found https://timeapi.io), but these are far less than countries and could end up being hardcoded, if we cannot find a suitable solution.

**Comment by lucasmenendez** [comment]
> That's giving us double work. If they were meaningful to users would be easier to understand for end developers too, but also, there would be no need to intercept them and map error codes to different error strings.

Is not double work, the difference between an API and a UI is that the first is designed to be used by other applications, and the second one is designed to be used by users. The UI probably needs more than a single API to complete a user action, and the different errors between APIs should be handled there to give the user a meaningful response, not just print errors.

I have no problem with creating specific errors for some cases and documenting them to be handled by others, like the UI (as the vochain and SDK do, for example), but i think that writing user messages in the API is an error and does not scale.

**Comment by elboletaire** [comment]
Note all this discussion comes from a message which isn't meaningful to either users nor developers. Personally I don't get the error "user not authorized" when trying to login. What's it saying? The account does not exist? My data is not correct?

**Comment by lucasmenendez** [comment]
As the API docs includes, the login endpoint returns four possible errors:
 * `400 Bad request`: `malformed JSON body` (when the request does not contains the data to complete the process.
 * `401 Unauthorized`: `user not authorized` (when the user is not found or the password does not match)
 * `401 Unauthorized`: `user account not verified` (where the user correct but the account is not verified yet)
 * `500 Internal Server Error` (if something unexpected occurs, such as db connection issues or errors building JWT token).
 
The reason to return a 401 instead of a 404 where the user is not found is because it is a security best practice to avoid giving away information about the existence or not of a particular user.

**Comment by elboletaire** [comment]
> Topics 2 & 4: the verification codes have an expiration time of [2 minutes](https://github.com/vocdoni/saas-backend/blob/23ed5ef6e18273d05e107c2e918cbc8636e9602b/api/const.go#L7). After this time, the expiration code is not valid and must be sent again. To manage this flow, there are two endpoints available, one to [check the information about a verification code by the email](https://github.com/vocdoni/saas-backend/blob/main/api/docs.md#-user-verification-code-info), and another to [resend a verification code to an unverified user](https://github.com/vocdoni/saas-backend/blob/main/api/docs.md#-resend-user-verification-code).

Correct me if I'm wrong, but the first one to check the status, shouldn't be public @lucasmenendez? Right now I'm on a loop since:
1. A user who did not verify an account tries to login
2. It fails with the "user not verified error".
3. I try to fetch the data to check if its latest invite code works and I cannot because it's protected
4. Therefore I cannot decide if I should send the verification code again

**Comment by jpaulet** [comment]
> Regarding the country list, it does not make sense to me to serve a list of countries from the backend. I understood that the front will get from an external API like the timezones for example.
> 
> @jpaulet

Yes, we can use an external free API for countries / timezones. Let's review the options and use one that fits our needs and it's easy to use.

**Comment by lucasmenendez** [comment]
> > Topics 2 & 4: the verification codes have an expiration time of [2 minutes](https://github.com/vocdoni/saas-backend/blob/23ed5ef6e18273d05e107c2e918cbc8636e9602b/api/const.go#L7). After this time, the expiration code is not valid and must be sent again. To manage this flow, there are two endpoints available, one to [check the information about a verification code by the email](https://github.com/vocdoni/saas-backend/blob/main/api/docs.md#-user-verification-code-info), and another to [resend a verification code to an unverified user](https://github.com/vocdoni/saas-backend/blob/main/api/docs.md#-resend-user-verification-code).
> 
> Correct me if I'm wrong, but the first one to check the status, shouldn't be public @lucasmenendez? Right now I'm on a loop since:
> 
> 1. A user who did not verify an account tries to login
> 2. It fails with the "user not verified error".
> 3. I try to fetch the data to check if its latest invite code works and I cannot because it's protected
> 4. Therefore I cannot decide if I should send the verification code again
> 
> Edit: looking at the docs, seems like the resend path is also protected (?)

Both endpoints are public: 
* https://github.com/vocdoni/saas-backend/blob/42de217ee2518699140df63c684aea7c4b1c47ff/api/api.go#L157
* https://github.com/vocdoni/saas-backend/blob/42de217ee2518699140df63c684aea7c4b1c47ff/api/api.go#L160

**Comment by elboletaire** [comment]
Weird, I'll try again but the beha ior I was having yesterday was returning me unauthorized, and the docs show the 401 error as an option for both calls

**Comment by lucasmenendez** [comment]
@elboletaire Both endpoints should return `401` only if the email provided has not any verification code associated in the database or something was wrong with the database connection. But lets review the flow.

**Comment by elboletaire** [comment]
Thanks for double checking @lucasmenendez, I'll give it a try again when I'm back home.

**Comment by elboletaire** [comment]
> The reason to return a 401 instead of a 404 where the user is not found is because it is a security best practice to avoid giving away information about the existence or not of a particular user.

Absolutely agree there. You can actually ignore most of what I said that week, I wasn't thinking clearly, and the "Unauthorized" change to "User not authorized" simply blow my (ill) mind.

> UPDATED: I've already checked and both endpoints are working as expected for me. I got the verification info when it was valid and expired, and I was able to resend a new code when it expired.

It was actually an error on my side, trying to make public calls with an (undefined) authorization header.

I've made a PR with a fix for 4 (see https://github.com/vocdoni/ui-scaffold/pull/829). I thought it was for 2 too, but re-reading that issue I see this does not fix it and actually I don't know how that behavior could be fixed. I guess improving the text error would be enough, telling the user to wait for 2 minutes before trying again, in which point it would be resent again... but I'm not liking the overall flow here TBH. Let me know your thoughts, guys.

PS: I edited the main issue to show what's been done already.

**Comment by lucasmenendez** [comment]
I have some ideas:
1. The UI should warn to the user about the expiration time before sending the verification code. Something like *"You'll receive a code in your inbox to verify your identity"* below the email field.
2. When the code is sent to the user from the backend, the UI can show the remaining time where the code is valid, same that the user has to wait to get a new one (for example with a counter).

**Comment by jpaulet** [comment]
Yeah, I like both ideas. 

But for the 2nd point, maybe it would be easier to say something like: "Your code is valid until hh:ii dd/mm/yy" (the backend should inform about this) and for then use the counter only for showing the waiting time. Bc having 2 different counters is a bit weird imo.

**Comment by jpaulet** [comment]
@elboletaire @lucasmenendez como ha quedado el punto 2? Es el último punto que falta para poder cerrar esta issue.

**Comment by lucasmenendez** [comment]
> @elboletaire @lucasmenendez como ha quedado el punto 2? Es el último punto que falta para poder cerrar esta issue.

The 2nd point is solved in the backend side, as I answer [here](https://github.com/vocdoni/interoperability/issues/234#issuecomment-2444661222). The required endpoints to check the expiration time of a verification code and to resend it already exist.

**Comment by elboletaire** [comment]
No it's not resolved yet, but allow me to move it to this issue where I'm requesting a revamp of the verify page and let's keep track of it there: https://github.com/vocdoni/ui-scaffold/issues/840
